source 'ssh://gerrit.zhenguanyu.com:29418/ios-specs'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'ExerciseDemo' do
pod 'Masonry', '~> 1.1.0'
pod 'SDWebImage', '~> 5.7.1'
end
